version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://<username>:<password>@db:5432/todo_db  # Update with your credentials
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: <username>  # Use your username
      POSTGRES_PASSWORD: <password>  # Use your password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data: