# Generated by Django 5.1.2 on 2024-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esther', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstherPost',
        ),
    ]
